config/routes.rb
RottenMangoes::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  

  root 'movies#index'

  
  namespace :admin do
    resources :users
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
# this adds a method avatar_url, provides ways to access it. YOU SMART.

  has_many :reviews

  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: {only_integer: true}
  validates :description, presence: true
  # validates :poster_image_url, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_the_past

  def review_average
      reviews.sum(:rating_out_of_ten)/reviews.size
  end

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ? OR director like ? OR runtime_in_minutes < ? OR runtime_in_minutes > ?", "%#{query}%", "%#{query}%", 90, 120)
  end
  
protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end
    
end
# where("title like ? OR director like ? OR runtime_in_minutes < ? OR runtime_in_minutes > ?", "%#{query}%", "%#{query}%", 90, 120)

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: {only_integer: true}
  validates :rating_out_of_ten, numericality: { greater_than_or_equal_to: 1}
  validates :rating_out_of_ten, numericality: {less_than_or_equal_to: 10}



end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reviews
  
  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 5..20}, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :only_for_admins

  def index
    @users = User.order(:id).page(params[:page]).per(10)
    @user = User.new
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(admin_user_params)

    if @user.save
      flash[:notice] = "User #{@user.full_name} created!"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(admin_user_params)
      flash[:notice] = "Successfully updated User."
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to admin_users_path

        # Tell the UserMailer to send a welcome email after save
      UserMailer.delete_user(@user).deliver
    end
  end
  


  protected

  def admin_user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
require 'pry'
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def only_for_admins
    if !current_user || !current_user.admin
      flash[:alert] = "You must be an admin to access that area."
      redirect_to movies_path
    end
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movie = Movie.new
    
    if (params[:search]) && (params[:duration] == "Search by Duration") 
      @movies = Movie.where("title like ? OR director like ?", "%#{params[:search]}%", "%#{params[:search]}%").order("created_at DESC")
    elsif params[:duration] == "Under 90 minutes"
      @movies = Movie.where("runtime_in_minutes <= ?", 90)
    elsif params[:duration] == "Between 90 and 120 minutes"
      @movies = Movie.where(runtime_in_minutes: 90..120)
    elsif params[:duration] ==  "Over 120 minutes"
      @movies = Movie.where("runtime_in_minutes > ?", 120)
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(:title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :avatar, :avatar_url)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  before_filter :restrict_access
  before_filter :load_movie

  def index
    @review = @movie.reviews.build
  end

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully."
    else
      render :new
    end
  end

protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

 def create
  user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed.."
      render :new
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "See ya!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

protected
  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<%= link_to "Back to admin page", admin_users_path %>
<h1>Edit User</h1>
<hr>
  <%= form_for([:admin, @user]) do |f| %>        
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div><%= f.submit "Submit" %></div>
  <% end %>

app/views/admin/users/index.html.erb
<%= link_to "Back to Movies", movies_path %><br> 

<h2>Admin Space</h2>
<hr>
<h5>Users list</h5>

<%= paginate @users %>
<div class="panel panel-default">
 <table class="table">
   <th>User ID</th>
   <th>Name</th>
   <th>Email</th>
   <th>Admin</th>
   <th>Created</th>
   <th>Updated</th>
   <th>Edit</th>
   <th>Delete</th>
   
   <% @users.each do |user| %>
   <tr>
   <td><%= user.id %></td>
   <td><%= user.full_name %></td>
   <td><%= user.email %></td>
   <% if user.admin %>
   <td><i class="fa fa-check"></i></td>
   <% else %>
   <td><i class="fa fa-close"></i></td>
   <% end %>
   <td><%= user.created_at.strftime('%B %Y') %></td>
   <td><%= user.updated_at.strftime('%B %Y') %></td>
   <td><%= link_to "Edit", edit_admin_user_path(user.id) %></a></td>
   <td><%= link_to "Delete", admin_user_path(user.id), method: :delete, data: { confirm: "Are you sure?" } %></td>
   </tr>
   <% end %>
 </table>
</div>



  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>


<div class="container">
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Create Users</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Create Users below</h4>
        </div>
        <div class="modal-body">
         
      <%= form_for([:admin, @user]) do |f| %>        
      <div>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :firstname, "First Name" %><br>
        <%= f.text_field :firstname %>
      </div>
      <div>
        <%= f.label :lastname, "Last Name" %><br>
        <%= f.text_field :lastname %>
      </div>
      <div>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div>
        <%= f.label :admin %><br>
        <%= f.check_box :admin %>
      </div>
      <div><%= f.submit "Submit" %></div>
      <% end %>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
  
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log in", new_session_path %> | <%= link_to "Sign up", new_user_path %>
    <% end %>


    <% if current_user && current_user.admin %>
       <%= link_to "Admin page", admin_users_path %>
    <% end %>

  </small>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" type="button"><%= image_tag "Drawing (2).png", id: "rotten_logo" %></a>
    </div>

    <ul class="nav navbar-nav navbar-right hidden-xs">
        <li><a href="#"><i class="fa fa-hand-peace-o"></i>Hi <% if current_user %><%= current_user.firstname %><% else %>Guest<% end %></a></li>
    </ul>
   
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
  <!-- Slick -->
<link href="https://kenwheeler.github.io/slick/slick/slick.css" rel="stylesheet"/>
<link href="https://kenwheeler.github.io/slick/slick/slick-theme.css" rel="stylesheet"/>
<!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>

</head>

<body>

<%= render 'layouts/nav' %>

<div class="container">
<!--<%= switch_user_select %>-->

<% flash.each do |key, value| %>
  <%= content_tag(:div, value) %>
<% end %>
<%= yield %>

</div>


<div class="container">
<hr>
<%= render 'layouts/footer' %>
</div>
<!-- Slick -->
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => {:multipart => true} do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <div class="form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :release_date %><br />
        <%= f.date_field :release_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :director %><br/>
        <%= f.text_field :director, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :runtime_in_minutes %><br/>
        <%= f.number_field :runtime_in_minutes, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br/>
        <%= f.text_field :description, class: "form-control" %>
      </div>
      <div class="form-group">
       <%= f.label :poster_image_url %><br>
       <%= f.text_field :poster_image_url, class: "form-control" %>
      </div>    
      <div class="form-group">
        <%= f.submit class: "btn btn-info" %>
      </div>
    </div>
  <div class="col-sm-2"></div>

<% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to all Movies", movies_path %>
<h1>Edit Movie</h1>
<hr>
<%= render 'form' %>

app/views/movies/index.html.erb
<div>
  <h4 style="text-align:center; color:#FF8800;">Welcome to Rotten Bananas! This is a space where users can view, search, and rate movies.  Users can also add their own movies to the collection! Enjoy!</h4>
</div>

<!-- Search by movie/director -->
<%= form_tag(movies_path, :method => "get", id: "search-form") do %>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <label for="inputEmail" class="col-lg-2 control-label">Movie/Director</label>  
      <div class="form-group">    
        <%= text_field_tag :search, params[:search], placeholder: "Search Movies/Directors", class: "form-control" %>
      </div>
      <!-- Search by Duration of movies -->
      <div class="form-group">
        <label for="select" class="col-lg-2 control-label">Duration</label>
        <%= select_tag :duration, options_for_select(["Search by Duration", "Under 90 minutes", "Between 90 and 120 minutes", "Over 120 minutes"], params[:duration]), class: "form-control", id: "select" %>
      </div>

      <div class="form-group" style="text-align:center;">
        <button type="reset" class="btn btn-default">Cancel</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
<% end %>

<hr>


<div class="movie-slider">
  <% @movies.each do |movie| %>
  <div class="col-md-5">
    <a type="button" data-toggle="modal" data-target="#movie<%= movie.id %>">
      <%= image_tag(movie.poster_image_url)%>
      <h5><%= truncate(movie.title, length: 20)%></h5> 
    </a> 
      <div class="hearts">
      <% if movie.reviews.any? %>
            <%= (movie.review_average).times.collect{'♥'}.join(' ') %> 
            <%= (10 - movie.review_average).times.collect{'♡'}.join(' ') %>
          <% else %>
           <%= 10.times.collect{'♡'}.join(' ') %>
          <% end %>
      </div>
      <h6><%= formatted_date(movie.release_date) %></h6>
    </div>
  <% end %>
</div>

 <!-- Adding modal movie view option -->
 <% @movies.each do |movie| %>
  <div class="modal fade" id="movie<%= movie.id %>" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
          <div style="float:left;margin-right:10px">
          <% if movie.poster_image_url? %>
            <%= image_tag(movie.poster_image_url, :class => "uploadedImage") %>
          <% end %>
          </div>
          <h4 class="modal-title"><h2><%= movie.title %></h2> <h5>(<%= link_to "edit", edit_movie_path(movie) %>, <%= link_to "delete", movie_path(movie), method: :delete, data: {confirm: "you sure bruh?"} %>)</h5></h4>
          <% if movie.reviews.any? %>
            <h3>Ratings: <%= movie.review_average %>/10</h3>
          <% end %>
          <div class="hearts">
            <% if movie.reviews.any? %>
              <%= (movie.review_average).times.collect{'♥'}.join(' ') %> 
              <%= (10 - movie.review_average).times.collect{'♡'}.join(' ') %>
            <% else %>
              <%= 10.times.collect{'♡'}.join(' ') %>
            <% end %>
          </div>
           
           <h3>Release Date: <%= formatted_date(movie.release_date) %></h3>
           <h4>Director: <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes </h4>
           <p><%= movie.description %></p>
        </div>
        <div class="modal-body">

          <h3>Reviews of <em><%= movie.title %></em></h3>
            <% movie.reviews.each do |review| %>
              <p><%= review.text %></p>
              <p><%= review.rating_out_of_ten %>/10</p>
              <small>- <% review.user.full_name %></small>
            <% end %>
          <% if current_user %>
            <p><%= link_to "Write a review!", new_movie_review_path(movie) %></p>
          <% else %>
            <p>Please <%= link_to "log in", new_session_path %> to add your own reviews. </p>
          <% end %>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

  
  <!-- Trigger the modal with a button -->
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add a movie</button>
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">   
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body clearfix">
          <h1 style="text-align:center;">Add Movie</h1>
          <hr>
          <%= render 'form' %>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
        </div>
      </div>      
    </div>
  </div>



<style>
  .movie-slider img {
    height: 200px;
  }
</style>




  

app/views/movies/new.html.erb
<div id="backtomovies">
  <%= link_to "Back to all Movies", movies_path %>
</div>
<h1>Add Movie</h1>
<hr>
<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to Movies", movies_path %><br> 

  <% if @movie.poster_image_url? %>
    <%= image_tag(@movie.poster_image_url, :class => "uploadedImage") %>

  <% end %>

  <h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, data: {confirm: "you sure bruh?"} %>)</h2>  
  
  <% if @movie.reviews.any? %>
    <h3>Ratings: <%= @movie.review_average %>/10</h3>
  <% end %>
  <div class="hearts">
  <% if @movie.reviews.any? %>
        <%= (@movie.review_average).times.collect{'♥'}.join(' ') %> 
        <%= (10 - @movie.review_average).times.collect{'♡'}.join(' ') %>
      <% else %>
       <%= 10.times.collect{'♡'}.join(' ') %>
      <% end %>
  </div>
 
  <h3>Release Date: <%= formatted_date(@movie.release_date) %></h3>
  <h4>Director: <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes </h4>
  <p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <% review.user.full_name %></small>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own. </p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>
<h2 style="text-align:center;">Write a review of <em><%= @movie.title %></em></h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :text %><br>
        <%= f.text_area "text", class: "form-control", style: "max-width:100%;" %>
      </div>
      <div class="form-group">
        <%= f.label :rating_out_of_ten %><br>
        <%= f.number_field :rating_out_of_ten, class: "form-control" %>
      </div>
      <div><%= f.submit "Submit", class: "btn btn-default" %></div>
    </div>
  <div class="col-md-3"></div>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1 style="text-align: center;">Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :firstname, "First Name" %><br>
        <%= f.text_field :firstname, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :lastname, "Last Name" %><br>
        <%= f.text_field :lastname, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div><%= f.submit "Submit", class: "btn btn-default" %></div>
    </div>
  <div class="col-md-3"></div>
<% end %>